CREATE INDEX "idx_assignment_questions_assignment_id" ON "assignment_questions" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "idx_assignment_submissions_assignment_id" ON "assignment_submissions" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "idx_assignment_submissions_student_id" ON "assignment_submissions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_assignment_submissions_status" ON "assignment_submissions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_assignments_teacher_id" ON "assignments" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "idx_assignments_subject_id" ON "assignments" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_assignments_curso_id" ON "assignments" USING btree ("curso_id");--> statement-breakpoint
CREATE INDEX "idx_assignments_periodo_lectivo_id" ON "assignments" USING btree ("periodo_lectivo_id");--> statement-breakpoint
CREATE INDEX "idx_assignments_teacher_subject_curso" ON "assignments" USING btree ("teacher_id","subject_id","curso_id");--> statement-breakpoint
CREATE INDEX "idx_chat_messages_session_id" ON "chat_messages" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_chat_sessions_user_id" ON "chat_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_chat_sessions_subject_id" ON "chat_sessions" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_cursos_profesor_id" ON "cursos" USING btree ("profesor_id");--> statement-breakpoint
CREATE INDEX "idx_direct_messages_sender_id" ON "direct_messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "idx_direct_messages_receiver_id" ON "direct_messages" USING btree ("receiver_id");--> statement-breakpoint
CREATE INDEX "idx_horarios_curso_id" ON "horarios" USING btree ("curso_id");--> statement-breakpoint
CREATE INDEX "idx_horarios_subject_id" ON "horarios" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_modules_subject_id" ON "modules" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_periodos_lectivos_activo" ON "periodos_lectivos" USING btree ("activo");--> statement-breakpoint
CREATE INDEX "idx_practice_answers_session_id" ON "practice_answers" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_practice_answers_user_id" ON "practice_answers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_practice_answers_subject_id" ON "practice_answers" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_practice_answers_is_correct" ON "practice_answers" USING btree ("is_correct");--> statement-breakpoint
CREATE INDEX "idx_practice_sessions_user_id" ON "practice_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_practice_sessions_subject_id" ON "practice_sessions" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_progress_user_id" ON "progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_progress_subject_id" ON "progress" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_progress_user_subject" ON "progress" USING btree ("user_id","subject_id");--> statement-breakpoint
CREATE INDEX "idx_submission_answers_submission_id" ON "submission_answers" USING btree ("submission_id");--> statement-breakpoint
CREATE INDEX "idx_user_progress_user_id" ON "user_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_progress_user_node_status" ON "user_progress" USING btree ("user_id","node_id","status");--> statement-breakpoint
CREATE INDEX "idx_users_role" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_users_activo" ON "users" USING btree ("activo");